name: "Terraform CI/CD"

on:
  push:
    paths:
      - "terraform/**"
      - ".github/workflows/terraform.yml"
    branches:
      - main
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/terraform.yml"

jobs:
  terraform:
    name: "Terraform Format, Validate & Plan"
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        environment: [dev, prod]

    defaults:
      run:
        working-directory: terraform/environments/${{ matrix.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: terraform

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          export_environment_variables: true
          create_credentials_file: true

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Extract Service Account Email
        id: extract-email
        run: |
          echo "service_account_email=$(echo '${{ secrets.GCP_CREDENTIALS }}' | jq -r '.client_email')" >> $GITHUB_OUTPUT
          echo "project_id=$(echo '${{ secrets.GCP_CREDENTIALS }}' | jq -r '.project_id')" >> $GITHUB_OUTPUT

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan Development
        if: github.event_name == 'pull_request' && matrix.environment == 'dev'
        id: plan-dev
        run: |
          terraform plan -no-color -input=false \
            -var-file="terraform.tfvars" \
            -var="project_id=${{ steps.extract-email.outputs.project_id }}" \
            -var="terraform_service_account_email=${{ steps.extract-email.outputs.service_account_email }}" \
            -out=tfplan-dev

      - name: Terraform Plan Production
        if: github.ref == 'refs/heads/main' && matrix.environment == 'prod'
        id: plan-prod
        run: |
          terraform plan -no-color -input=false \
            -var-file="terraform.tfvars" \
            -var="project_id=${{ steps.extract-email.outputs.project_id }}" \
            -var="terraform_service_account_email=${{ steps.extract-email.outputs.service_account_email }}" \
            -out=tfplan-prod

      - name: Upload Development Plan
        if: github.event_name == 'pull_request' && matrix.environment == 'dev'
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-dev
          path: terraform/environments/dev/tfplan-dev
          retention-days: 5

      - name: Upload Production Plan
        if: github.ref == 'refs/heads/main' && matrix.environment == 'prod'
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-prod
          path: terraform/environments/prod/tfplan-prod
          retention-days: 5

  deploy:
    name: "Deploy Infrastructure"
    needs: terraform
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    timeout-minutes: 45
    environment:
      name: production

    defaults:
      run:
        working-directory: terraform/environments/prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          export_environment_variables: true
          create_credentials_file: true

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Extract Service Account Email
        id: extract-email
        run: |
          echo "service_account_email=$(echo '${{ secrets.GCP_CREDENTIALS }}' | jq -r '.client_email')" >> $GITHUB_OUTPUT
          echo "project_id=$(echo '${{ secrets.GCP_CREDENTIALS }}' | jq -r '.project_id')" >> $GITHUB_OUTPUT

      - name: Update Environment URL
        run: |
          echo "ENVIRONMENT_URL=https://console.cloud.google.com/home/dashboard?project=${{ steps.extract-email.outputs.project_id }}" >> $GITHUB_ENV

      - name: Download Production Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan-prod
          path: terraform/environments/prod

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Apply Production
        run: terraform apply -auto-approve "tfplan-prod"
